CREATE TABLE MOVIE (
    MOVIE_ID NUMBER(10) PRIMARY KEY,
    MOVIE_TITLE VARCHAR2(150),
    IMDB_ID NUMBER(10),
    MOVIE_SPANISHTITLE VARCHAR2(150),
    IMDB_PICURL VARCHAR2(150),
    RELEASE_YEAR NUMBER(4),
    rtID VARCHAR2(150),
    rtAllCriticsRating NUMBER(7, 2),
    rtAllCriticsNumReviews NUMBER(7),
    rtAllCriticsNumFresh NUMBER(7),
    rtAllCriticsNumRotten NUMBER(7),
    rtAllCriticsScore NUMBER(7, 2),
    rtTopCriticsRating	NUMBER(7, 2),
    rtTopCriticsNumReviews	NUMBER(7),
    rtTopCriticsNumFresh NUMBER(7),
    rtTopCriticsNumRotten NUMBER(7),
    rtTopCriticsScore NUMBER(7, 2),
    rtAudienceRating NUMBER(7, 2),
    rtAudienceNumRatings NUMBER(7),
    rtAudienceScore	NUMBER(7, 2),
    rtPictureURL VARCHAR2(150)
);

CREATE INDEX MOVIE_MOVIE_ID_RELEASE_YEAR ON MOVIE(MOVIE_ID, RELEASE_YEAR);

CREATE TABLE MOVIE_GENRES (
    MOVIE_ID NUMBER(10),
    GENRES VARCHAR(20),
    PRIMARY KEY(MOVIE_ID, GENRES),
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE
    ON DELETE CASCADE
);

CREATE INDEX MOVIE_GENRES_MOVIE_ID ON MOVIE_GENRES(MOVIE_ID);

CREATE TABLE COUNTRIES (
    MOVIE_ID NUMBER(10),
    COUNTRY VARCHAR(30),
    PRIMARY KEY(MOVIE_ID),
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE
    ON DELETE CASCADE
);

CREATE TABLE LOCATIONS (
    MOVIE_ID NUMBER(10),
    LOCATION1 VARCHAR2(100),
    LOCATION2 VARCHAR2(100),
    LOCATION3 VARCHAR2(100),
    LOCATION4 VARCHAR2(150),
    PRIMARY KEY(MOVIE_ID, LOCATION1, LOCATION2, LOCATION3, LOCATION4),
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE
    ON DELETE CASCADE
);

CREATE INDEX LOCATIONS_MOVIE_ID ON LOCATIONS(MOVIE_ID);

CREATE TABLE TAGS (
    TAG_ID VARCHAR2(20) PRIMARY KEY,
    TAG_TEXT VARCHAR2(50)
);

CREATE TABLE MOVIE_TAGS (
    MOVIE_ID NUMBER(10),
    TAG_ID VARCHAR2(20),
    TAG_WEIGHT NUMBER(2),
    PRIMARY KEY(MOVIE_ID, TAG_ID),
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE
    ON DELETE CASCADE,
    FOREIGN KEY (TAG_ID) REFERENCES TAGS
    ON DELETE CASCADE
);

CREATE INDEX MOVIE_TAGS_MOVIE_ID ON MOVIE_TAGS(MOVIE_ID);

CREATE TABLE USER_RATEDMOVIES (
    USER_ID NUMBER(10),
    MOVIE_ID NUMBER(10),
    RATING NUMBER(7, 2),
    DATE_DAY NUMBER(2),
    DATE_MONTH NUMBER(2),
    DATE_YEAR NUMBER(4),
    DATE_HOUR NUMBER(2),
    DATE_MINUTE NUMBER(2),
    DATE_SECOND NUMBER(2),
    PRIMARY KEY (USER_ID, MOVIE_ID),
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE
    ON DELETE CASCADE
);

CREATE TABLE USER_RATEDMOVIES_TIMESTAMPS (
    USER_ID NUMBER(10),
    MOVIE_ID NUMBER(10),
    RATING NUMBER(7,2),
    M_TIMESTAMP NUMBER(20),
    PRIMARY KEY (USER_ID, MOVIE_ID),
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE
    ON DELETE CASCADE
);

CREATE TABLE USER_TAGGEDMOVIES (
    USER_ID VARCHAR2(20),
    MOVIE_ID VARCHAR2(20),
    TAG_ID VARCHAR2(20),
    DATE_DAY VARCHAR2(20),
    DATE_MONTH VARCHAR2(20),
    DATE_YEAR VARCHAR2(20),
    DATE_HOUR VARCHAR2(20),
    DATE_MINUTE VARCHAR2(20),
    DATE_SECOND VARCHAR2(20),
    PRIMARY KEY (USER_ID, MOVIE_ID, TAG_ID),
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE
    ON DELETE CASCADE,
    FOREIGN KEY (TAG_ID) REFERENCES TAGS
    ON DELETE CASCADE
);

CREATE TABLE USER_TAGGEDMOVIES_TIMESTAMPS (
    USER_ID VARCHAR2(20),
    MOVIE_ID VARCHAR2(20),
    TAG_ID VARCHAR2(20),
    M_TIMESTAMPS VARCHAR2(20),
    PRIMARY KEY (USER_ID, MOVIE_ID, TAG_ID),
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE
    ON DELETE CASCADE,
    FOREIGN KEY (TAG_ID) REFERENCES TAGS
    ON DELETE CASCADE
);
